spring.application.name=resource-server

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000

# DB and JPA
spring.datasource.url=jdbc:postgresql://localhost:5432/street-art-explorer-resource-server
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# DB migration (flyway)
spring.flyway.enabled=true
spring.flyway.validate-on-migrate=true